baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/XXX"
    twitter = "https://twitter.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
    
    
name = "ghostwriter"
license = "MIT"
licenselink = "https://github.com/jbub/ghostwriter/blob/master/LICENSE.md"
description = "A fork of simple AJAX driven theme for the Ghost blogging platform ported to Hugo."
homepage = "https://github.com/jbub/ghostwriter"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]
min_version = "0.41"



[original]
    author = "roryg"
    homepage = "http://ghost.jollygoodthemes.com/ghostwriter/"
    repo = "https://github.com/roryg/ghostwriter"
